### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by Zehaoc** [knelk/enerf#1]
Hi,
 I am writing to inquire about the possibility of obtaining a pre-trained model from you. I am a researcher in the field of event camera and have been following your work for some time now. Your contributions have been truly insightful and I believe that your pre-trained models would greatly benefit my work.
I understand that obtaining a pre-trained model can be a complex process, but I would be grateful if you could consider providing me with one for my research purposes. I assure you that I will use it solely for academic purposes and will properly cite your work in any publications that may result from its use.
Thanks!

**Comment by knelk** [comment]
Unfortunately, I do not have pretrained models available. However, you can train the models yourself easily, by using the provided config files & links to the data. For the real data (eds & tumvie) I also provided the data-conversion scripts. Hope this helps
