### ISSUE TITLE
encountered an error message: assert np.all(np.diff(tss_evs_centers_us)>0) AssertionError

### ISSUE THREAD

**Issue by Zehaoc** [knelk/enerf#4]
Hello knelk,
Thank you for all of your excellent work on this project. I'm currently working on running the "00_peanuts_dark" and "11_all_characters" dataset files from the eds datasets.
As a first step, I used the undistort_images_eds.py script to preprocess both datasets. However, when I began the training process, I encountered an error message:
`"assert np.all(np.diff(tss_evs_centers_us)>0) AssertionError" `
I'm wondering if I may have overlooked or missed a step in the preprocessing or setup. Could you please point me in the right direction as to what may be causing this error? Any insight would be greatly appreciated.
Thank you in advance for your help. Please let me know if you need any additional information from me.
Regards,
zehao

**Comment by knelk** [comment]
Hey, can you please provide more details? For example, what is  inside of ``tss_evs_centers_us``? 

Does this error occur for both sequences?
