### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by SharineLee** [knelk/enerf#7]
Got total events of 9999.999999999993ms, with pos/neg = 0.6745503882480726
Done with event and pose query.
Starting to compute 19 evs_dict_xy
Batch 1/19 dict from events and interpolated poses per event
Batch 2/19 dict from events and interpolated poses per event
Batch 3/19 dict from events and interpolated poses per event
Batch 4/19 dict from events and interpolated poses per event
Batch 5/19 dict from events and interpolated poses per event
Batch 6/19 dict from events and interpolated poses per event
Batch 7/19 dict from events and interpolated poses per event
Batch 8/19 dict from events and interpolated poses per event
Batch 9/19 dict from events and interpolated poses per event
Batch 10/19 dict from events and interpolated poses per event
Batch 11/19 dict from events and interpolated poses per event
Batch 12/19 dict from events and interpolated poses per event
Batch 13/19 dict from events and interpolated poses per event
Batch 14/19 dict from events and interpolated poses per event
Batch 15/19 dict from events and interpolated poses per event
Batch 16/19 dict from events and interpolated poses per event
Batch 17/19 dict from events and interpolated poses per event
Batch 18/19 dict from events and interpolated poses per event
Batch 19/19 dict from events and interpolated poses per event

Traceback (most recent call last):
  File "/home/sharine/LXX/MyResearch/enerf/main_nerf.py", line 226, in <module>
    train_loader = EventNeRFDataset(opt, device=device, type='train', downscale=opt.downscale, select_frames=select_frames).dataloader()
  File "/home/sharine/LXX/MyResearch/enerf/nerf/provider.py", line 1258, in __init__
    poses_batch = torch.from_numpy(np.asarray(poses)).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 810.00 MiB (GPU 0; 10.76 GiB total capacity; 8.80 GiB already allocated; 434.38 MiB free; 8.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Pacifica-H** [comment]
Hi, I met the same problem, I wonder how did you solve it?

**Comment by ImmaFake** [comment]
Hi, have you solved this problem？ I met exactly the same question. @SharineLee
