### ISSUE TITLE
About how to split event data in ESIM dataset

### ISSUE THREAD

**Issue by TomCC7** [knelk/enerf#8]
Hi, thanks for your project! 

I'm trying to build some new examples using ESIM that can be directly used on your project. However, I'm running into some issues trying to understand how you split your event data into multiple npy files. 

Originally I thought that you were just naively separating all the events that happen between two RGB frames into one batch (e.g. the events between $T_i$ and $T_{i+1}$), but seems that it's not the case. 

It will be very helpful if you can share your ideas on this, or share the scripts you use to convert rosbag files to your datasets. Thanks!

**Comment by knelk** [comment]
Hi Tom, the event npys are batched from T_i - dT / 2 to T_i + dT / 2, where dT = T_i+1 - T_i. Hope it helps, if not I can try to dig out the scripts.

**Comment by TomCC7** [comment]
Seems like this is correct, thank you!
